# Generated by Django 5.1.5 on 2025-02-28 10:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='banner_img', verbose_name='Картинка')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
                ('width', models.IntegerField(default=450, verbose_name='Ширина')),
                ('height', models.IntegerField(default=350, verbose_name='Высота')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата записи')),
                ('update_at', models.DateTimeField(verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннер',
                'db_table': 'banners',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Категория меню')),
                ('slug', models.SlugField(max_length=20, verbose_name='Slug')),
                ('icon_class', models.CharField(max_length=20, verbose_name='Класс для иконки')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название раздела')),
                ('slug', models.SlugField(max_length=20, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Навигация',
                'verbose_name_plural': 'Навигация',
                'db_table': 'navigation',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='product_img', verbose_name='Картинка')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Скидка в %')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'db_table': 'products',
            },
        ),
    ]
