# Generated by Django 5.1.5 on 2025-02-27 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='banner_img', verbose_name='Картинка')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
                ('width', models.IntegerField(default=450, verbose_name='Ширина')),
                ('height', models.IntegerField(default=350, verbose_name='Высота')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата записи')),
                ('update_at', models.DateTimeField(verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннер',
                'db_table': 'banners',
            },
        ),
    ]
